Repository bounswe/bounswe2019group6, pull requests merged in 2019-05, with the labels that each got.

#77 Events and currency
  practice-app/src/djangotut/README.md
  practice-app/src/djangotut/currencyrateapp/__init__.py
  practice-app/src/djangotut/currencyrateapp/admin.py
  practice-app/src/djangotut/currencyrateapp/apps.py
  practice-app/src/djangotut/currencyrateapp/forms.py
  practice-app/src/djangotut/currencyrateapp/migrations/__init__.py
  practice-app/src/djangotut/currencyrateapp/models.py
  practice-app/src/djangotut/currencyrateapp/templates/currency_index.html
  practice-app/src/djangotut/currencyrateapp/tests.py
  practice-app/src/djangotut/currencyrateapp/urls.py
  practice-app/src/djangotut/currencyrateapp/views.py
  practice-app/src/djangotut/djangotut/settings.py
  practice-app/src/djangotut/djangotut/urls.py
  practice-app/src/djangotut/eventsapp/__pycache__/__init__.cpython-37.pyc
  practice-app/src/djangotut/eventsapp/__pycache__/views.cpython-37.pyc
  practice-app/src/djangotut/eventsapp/admin.py
  practice-app/src/djangotut/eventsapp/apps.py
  practice-app/src/djangotut/eventsapp/models.py
  practice-app/src/djangotut/eventsapp/tests.py
  practice-app/src/djangotut/eventsapp/views.py
Labels: help wanted, priority:high, related:frontend, review

#78 The API for news has been added
  practice-app/src/djangotut/djangotut/settings.py
  practice-app/src/djangotut/djangotut/urls.py
  practice-app/src/djangotut/newsapp/admin.py
  practice-app/src/djangotut/newsapp/apps.py
  practice-app/src/djangotut/newsapp/models.py
  practice-app/src/djangotut/newsapp/tests.py
  practice-app/src/djangotut/newsapp/views.py
Labels: priority:medium, review

#84 Currency rate enhancement
  practice-app/src/djangotut/currencyrateapp/forms.py
  practice-app/src/djangotut/currencyrateapp/templates/currency_index.html
  practice-app/src/djangotut/currencyrateapp/tests.py
  practice-app/src/djangotut/currencyrateapp/urls.py
  practice-app/src/djangotut/currencyrateapp/views.py
Labels: priority:high, related: feedback, related:backend, related:frontend, type:new-feature, type:project-task
